services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - ./configs/envfiles/.postgres.dev.env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgweb:
    image: sosedoff/pgweb
    restart: always
    env_file:
      - ./configs/envfiles/.pgweb.dev.env
    ports:
      - 127.0.0.1:8081:8081
    depends_on:
      - postgres
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    restart: on-failure:10
    env_file:
      - ./configs/envfiles/.app.dev.env
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres
volumes:
  postgres-data: