// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RbacPvtUserRole struct {
	ID        int32            `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	UserID    int32            `json:"user_id"`
	RoleID    int32            `json:"role_id"`
}

type RbacRole struct {
	ID          int32            `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	Permissions []string         `json:"permissions"`
}

type RbacUser struct {
	ID            int32            `json:"id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	FirstName     *string          `json:"first_name"`
	LastName      *string          `json:"last_name"`
	Username      string           `json:"username"`
	Password      *string          `json:"password"`
	Email         string           `json:"email"`
	Description   *string          `json:"description"`
	AccountLocked bool             `json:"account_locked"`
	PathToAvatar  *string          `json:"path_to_avatar"`
	Permissions   []string         `json:"permissions"`
}

type RbacUserLogin struct {
	ID           int32            `json:"id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	TerminatedAt pgtype.Timestamp `json:"terminated_at"`
	UserID       int32            `json:"user_id"`
	Successful   bool             `json:"successful"`
	IpAddress    string           `json:"ip_address"`
	UserAgent    string           `json:"user_agent"`
}
